In [1]:
!pip install sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 79 kB 5.2 MB/s 
     |████████████████████████████████| 4.4 MB 21.6 MB/s 
     |████████████████████████████████| 1.2 MB 46.6 MB/s 
     |████████████████████████████████| 101 kB 13.2 MB/s 
     |████████████████████████████████| 596 kB 42.4 MB/s 
     |████████████████████████████████| 6.6 MB 61.8 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.0-py3-none-any.whl size=120747 sha256=5f5b5e6c96c652584fa1457b30289bda8bb596c3ff4f5fe5e46345fbecc2ab31
  Stored in directory: /root/.cache/pip/wheels/83/c0/df/b6873ab7aac3f2465aa9144b6b4c41c4391cfecc027c8b07e7
Successfully built sentence-transformers
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
pip install faiss

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 14.4 MB/s 


In [ ]:
# !wget  https://anaconda.org/pytorch/faiss-cpu/1.2.1/download/linux-64/faiss-cpu-1.2.1-py36_cuda9.0.176_1.tar.bz2
# !tar xvjf faiss-cpu-1.2.1-py36_cuda9.0.176_1.tar.bz2
# !cp -r lib/python3.6/site-packages/* /usr/local/lib/python3.6/dist-packages/
# !pip install mkl

In [3]:
!sudo apt-get install libomp-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libomp5
Suggested packages:
  libomp-doc
The following NEW packages will be installed:
  libomp-dev libomp5
0 upgraded, 2 newly installed, 0 to remove and 49 not upgraded.
Need to get 239 kB of archives.
After this operation, 804 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp5 amd64 5.0.1-1 [234 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp-dev amd64 5.0.1-1 [5,088 B]
Fetched 239 kB in 1s (343 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 2.)
deb

In [45]:
!pip install gradio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.1 MB 16.4 MB/s 
     |████████████████████████████████| 2.0 MB 57.8 MB/s 
     |████████████████████████████████| 53 kB 2.2 MB/s 
     |████████████████████████████████| 1.1 MB 63.2 MB/s 
     |████████████████████████████████| 140 kB 83.9 MB/s 
     |████████████████████████████████| 256 kB 82.4 MB/s 
     |████████████████████████████████| 54 kB 3.4 MB/s 
     |████████████████████████████████| 84 kB 3.6 MB/s 
     |████████████████████████████████| 212 kB 78.8 MB/s 
     |████████████████████████████████| 271 kB 81.6 MB/s 
     |████████████████████████████████| 144 kB 66.6 MB/s 
     |████████████████████████████████| 94 kB 3.7 MB/s 
     |████████████████████████████████| 63 kB 2.2 MB/s 
     |████████████████████████████████| 80 kB 10.4 MB/s 
     |████████████████████████████████| 43 kB 2.2 MB/s 
     |████████████████████████████████| 4.0 

In [46]:
import pandas as pd
import faiss
import pickle
import gradio as gr

In [5]:
df = pd.read_csv('/content/drive/MyDrive/df_klasyfikacja_small.csv')

In [7]:
df.sample()

Unnamed: 0 section              byline  \
125         125  Health  Annabelle Williams   

                                                 title  \
125  Patricia Moreno, Spiritual Fitness Leader, Die...   

                                              abstract class  print_page  \
125  Ms. Moreno’s intenSati program helped bring po...   top         0.0   

    pub_date type_of_material  class_le  ...                 title_ner_type  \
125      NaN              NaN         1  ...  ['PERSON', 'ORG', 'CARDINAL']   

     ners_num  ner_GPE ner_PERSON ner_ORG  ner_MONEY  ner_NORP  \
125         3      0.0        1.0     0.0        0.0       0.0   

     pub_day_of_week  title_sentiment  abstract_sentiment  
125             -1.0           0.2732              0.5574  

[1 rows x 40 columns]

In [8]:
titles = df['title'].tolist()

In [9]:
len(titles)

1210

In [10]:
# remove duplicates and NaN
titles = [word for word in list(set(titles)) if type(word) is str]

In [11]:
from sentence_transformers import SentenceTransformer
# initialize sentence transformer model
model = SentenceTransformer('bert-base-nli-mean-tokens')

/usr/local/lib/python3.7/dist-packages/huggingface_hub/snapshot_download.py:11: FutureWarning: snapshot_download.py has been made private and will no longer be available from version 0.11. Please use `from huggingface_hub import snapshot_download` to import the only public function in this module. Other members of the file may be changed without a deprecation notice.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py:563: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  FutureWarning,


Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [12]:
# create sentence embeddings
sentence_embeddings = model.encode(titles, show_progress_bar=True)
sentence_embeddings.shape

Batches:   0%|          | 0/38 [00:00<?, ?it/s]

(1208, 768)

In [13]:
#Store sentences & embeddings on disc
with open('embeddings_small.pkl', "wb") as fOut:
    pickle.dump({'sentences': titles, 'embeddings': sentence_embeddings}, fOut, protocol=pickle.HIGHEST_PROTOCOL)

In [16]:
#Load sentences & embeddings from disc
with open('/content/drive/MyDrive/embeddings_small.pkl', "rb") as fIn:
    stored_data = pickle.load(fIn)
    stored_sentences = stored_data['sentences']
    sentence_embeddings = stored_data['embeddings']

In [17]:
d = sentence_embeddings.shape[1]
d

768

In [18]:
index = faiss.IndexFlatL2(d)

In [19]:
index.is_trained

True

In [20]:
index.add(sentence_embeddings)

In [21]:
index.ntotal

1208

In [23]:
df['title'].iloc[0]

'‘I’ll Stand on the Side of Russia’: Pro-Putin Sentiment Spreads Online'

In [39]:
k = 4
xq = model.encode(['‘I’ll Stand on the Side of Russia’: Pro-Putin Sentiment Spreads Online.'])

In [40]:
%%time
D, I = index.search(xq, k)  # search
print(I)

[[968 471 430 998]]
CPU times: user 3.95 ms, sys: 1.01 ms, total: 4.96 ms
Wall time: 8.7 ms


In [43]:
df['title'].iloc[[968, 471, 430, 998]]

968    Mandy Patinkin Finds Healing in Refugee Work a...
471    U.S. schools are back in person, but many chil...
430           The Outsider Art Fair Returns, in Top Form
998    Spring Is Here! Here’s How to Spot the Seasona...
Name: title, dtype: object

In [27]:
nlist = 50  # how many Voronoi cells
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)

In [28]:
index.is_trained

False

In [29]:
index.train(sentence_embeddings)
index.is_trained  # check if index is now trained

True

In [30]:
index.add(sentence_embeddings)
index.ntotal  # number of embeddings indexed

1208

In [31]:
%%time
D, I = index.search(xq, k)  # search
print(I)

[[968 471 430 998]]
CPU times: user 1.84 ms, sys: 0 ns, total: 1.84 ms
Wall time: 1.75 ms


In [ ]:
df['headline.main'].iloc[[20064, 49408, 46605, 10547]]

20064    For U.K.’s Johnson, Plenty of Mud but Will It ...
49408    3 Officers Used Excessive Force in Arrest of B...
46605                                   Spelling Bee Forum
10547                           Corrections: Feb. 24, 2021
Name: headline.main, dtype: object

In [32]:
index.nprobe = 10

In [33]:
%%time
D, I = index.search(xq, k)  # search
print(I)

[[968 471 430 998]]
CPU times: user 5.02 ms, sys: 986 µs, total: 6 ms
Wall time: 6.9 ms


In [ ]:
df['headline.main'].iloc[[20064, 49408, 46605, 10547]]

20064    For U.K.’s Johnson, Plenty of Mud but Will It ...
49408    3 Officers Used Excessive Force in Arrest of B...
46605                                   Spelling Bee Forum
10547                           Corrections: Feb. 24, 2021
Name: headline.main, dtype: object

Próba na nieistniejących danych

In [98]:
k = 4
xq = model.encode(['Cats and dogs'])

In [99]:
%%time
D, I = index.search(xq, k)  # search
print(I)

[[ 787  822  338 1189]]
CPU times: user 414 µs, sys: 13 µs, total: 427 µs
Wall time: 434 µs


In [102]:
df['title'].iloc[[787,  822,  338, 1189]]

787     In Burundi, the Drum Is a Revered Symbol of Un...
822     In These Women’s Hands, Dating Is Truly the St...
338     Curious About ‘Moon Knight’? Here’s What You N...
1189    A Thriller Wrapped in a Story of Sisters and F...
Name: title, dtype: object

In [75]:
def model_gradio(Title):
  k = 1
  xq = model.encode([Title])
  D, I = index.search(xq, k) 
  a = df['title'].iloc[I.item()]
  return a

In [126]:
def model_gradio(Title, Number):
  k = int(Number)
  xq = model.encode([Title])
  D, I = index.search(xq, k) 
  lista=[]
  for i in range(k):
    lista.append(I.item(i))
  a = pd.DataFrame(df['title'].iloc[lista])
  return a

In [128]:
demo = gr.Interface(
    fn=model_gradio,
    inputs=[
       'text', 'number'
       ],
    outputs=['numpy'],
    title='Similar articles',
    description='Enter the title and number of similar articles you want to find'
)

demo.launch()

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://20422.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)


(<gradio.routes.App at 0x7fc292155190>,
 'http://127.0.0.1:7869/',
 'https://20422.gradio.app')